### PR TITLE
Use bot name as command name, and add @name aliases. Closes #52.

### LINKED ISSUE #52: allow talking to pombot directly
I spent a few minutes trying to ask it for help and telling it things, I was super confused

### PR DESCRIPTION
**Pull request by cowboy**
You should be able to, in a public channel or DM, address the bot with:

* `botname`
* `botname:`
* `@botname`
* `@botname:`

eg.

* `botname`
* `botname:`
* `botname: help`
* `@botname: i will do something`

Assitionally, in a DM, you should be able to omit the name/alias, eg.

* `help`
* `i will do something`

### CODE REVIEW

**Comment by tkellen** [comment]
cc @jennschiffer 

Before we land this we need to update the pombot image and docs on the homepage

**Comment by cowboy** [comment]
(please test this btw!)

**Comment by jennschiffer** [comment]
👍

**Comment by cowboy** [comment]
Feel free to merge if it's good for you!

**Pull request merged**
