### PR TITLE
have messaging work when poms are in multiple teams

### PR DESCRIPTION
**Pull request by jennschiffer**
this is a bug fix where one team would update the alert/complete status of literally every pom record

### CODE REVIEW

**Comment by tkellen** [comment]
What do you think about combining `update_team_poms_set_alerted.sql` and `update_team_poms_set_completed.sql` to `update_teams_pom_flags.sql` and accepting alerted/completed values?

**Comment by tkellen** [comment]
scratch that

/ref https://github.com/vitaly-t/pg-promise/issues/173

**Comment by vitaly-t** [comment]
>scratch that

did you mean `scrap`? :smile:

**Comment by tkellen** [comment]
both work--english is super flexible!

**Comment by tkellen** [comment]
:+1:

**Pull request merged**
