### PR TITLE
Secrets / consistency fixes. Closes #74.

### LINKED ISSUE #74: Update secrets fetching / var names.
To work with the new format in `/var/mnt/secrets/rds-bocoup-db`.

### PR DESCRIPTION
**Pull request by cowboy**
This PR contains these fixes:

* Fix npm-shrinkwrap issue with fsevents.
* Update secrets fetching / var names.
* Add `db:create` and `db:drop` npm scripts.
* Move secrets fetching into a separate ansible role.
* Update secrets and upstart script template.
* Ensure `pombot` upstart script is restarted after a deploy.
* Use existing `node_modules` if `package.json` hasn't changed.
* Add hidden `version` command to help in troubleshooting bot issues.

### CODE REVIEW

**Comment by jennschiffer** [comment]
is there a reason why the name of the service needs to be changed

**Comment by cowboy** [comment]
> is there a reason why the name of the service needs to be changed

Nope, I was just trying to make it consistent with the work I had done on skillsbot. I can change it back, if the name is important or if it makes things easier!

**Comment by jennschiffer** [comment]
i'd prefer the name to stay the same, especially as it will mean i don't have to manually stop and remove it. otherwise everything else looks great!

**Comment by cowboy** [comment]
Ok, I'll revert the change. No prob.

**Comment by cowboy** [comment]
I rebased everything, it should be all set. Please test though, in case I messed anything up!

**Comment by tkellen** [comment]
Great work @cowboy! This has been deployed and it's working perfectly.

**Pull request merged**
