### PR TITLE
Add support for testing deployment in vagrant. Closes #79.

### LINKED ISSUE #79: Add vagrant config/playbooks for testing deployment
See https://github.com/bocoup/bots/pull/161/commits

### PR DESCRIPTION
**Pull request by cowboy**
Testing instructions: https://github.com/bocoup/pombot/wiki/Deployment

### CODE REVIEW

**Comment by cowboy** [comment]
FWIW, before I did the above, I did:

1. `npm run get-secrets`
1. created a new slack app using `https://pombot.loc` and `https://pombot.loc/authorize` for the urls (don't forget to add a bot)
1. modified the `.env` file `SLACK_CLIENT_ID` and `SLACK_CLIENT_SECRET` to match my new slack app's credentials
1. modified the `.env` file `PGNAME` value to `pombot-ben`
1. `npm run db:create`
1. `npm run migrate:up`

Then, for steps 3-4 above, I really did this:

* `cat .env | sed 's/^/env /' | pbcopy`
* `ssh -t pombot.loc sudo vim /etc/init/pombot.conf`
* `7j8C` then _cmd-V_ then _esc_ then `:wq`

**Comment by tkellen** [comment]
after much self-inflicted teeth gnashing, i am giving this a :+1:

**Comment by tkellen** [comment]
cc @jennschiffer for final sign off

**Comment by cowboy** [comment]
I'm making a slight tweak to the upstart script. NBD, gimme a min.

**Comment by cowboy** [comment]
Ok, done. @tkellen @jennschiffer as part of this, can you also review the Depoyment docs and updated Development docs?

* https://github.com/bocoup/pombot/wiki/Deployment
* https://github.com/bocoup/pombot/wiki/Development

Thanks!

**Comment by tkellen** [comment]
In the "Deploy and test the slack app" section it could be a little more clear that the three provided examples are examples, not three commands you should specifically run.

**Comment by tkellen** [comment]
Other than that, :+1:!

**Comment by cowboy** [comment]
Ok, done!

**Comment by jennschiffer** [comment]
👍

**Pull request merged**
