### PR TITLE
Allow easy psql db connection with "npm run db".

### PR DESCRIPTION
**Pull request by cowboy**
```bash
$ npm run db

> pombot@0.0.1 db /Users/cowboy/repos/bocoup/pombot
> source .env && PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER $DB_NAME

psql (9.5.3, server 9.4.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

pombot_cowboy=>
```

### CODE REVIEW

**Comment by cowboy** [comment]
@tkellen thoughts?

**Comment by tkellen** [comment]
:+1:

**Comment by tkellen** [comment]
looks like you need to rebase tho?

**Comment by cowboy** [comment]
Hmmn. Let me try. Weird, I thought I just did.

**Pull request merged**
